append execute

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,3 +1,149 @@
+# name: Deploy Streamlit App
+
+# on:
+#   push:
+#     branches:
+#       - main # or your default branch
+
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+    
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
+
+#     - name: Set up Docker Buildx
+#       uses: docker/setup-buildx-action@v1
+
+#     - name: Login to Docker Hub
+#       run: docker login -u ${{ secrets.DOCKER_USERNAME_DATAOS }} -p ${{ secrets.DOCKER_PASSWORD_DATAOS }}
+
+#     - name: Pull Docker image
+#       run: docker pull rubiklabs/dataos-ctl:2.10.9-dev
+
+#     - name: Run Docker container
+#       run: docker run rubiklabs/dataos-ctl:2.10.9-dev
+
+#     - name: Find YAML file
+#       run: |
+#         file=$(find . -name "cluster.yaml" -printf "%P\n" -quit)
+#         echo "Found file: $file"
+#         echo "file=$file" >> $GITHUB_ENV
+
+#     - name: Get commit author
+#       id: get_author
+#       run: |
+#         commit_author=$(git log -1 --format='%an')
+#         echo "Commit author is $commit_author"
+#         echo "author=$commit_author" >> $GITHUB_ENV
+
+#     - name: Set API Key and User ID
+#       id: set_env
+#       run: |
+#         if [ "${{ env.author }}" == "shreya negi" ]; then
+#           echo "USER_ID=${{ secrets.SHREYA_USERNAME }}" >> $GITHUB_ENV
+#           echo "API_KEY=${{ secrets.SHREYA_API_KEY }}" >> $GITHUB_ENV
+#         elif [ "${{ env.author }}" == "itsyourdj" ]; then
+#           echo "USER_ID=${{ secrets.DEEPAK_USERNAME }}" >> $GITHUB_ENV
+#           echo "API_KEY=${{ secrets.DEEPAK_API_KEY }}" >> $GITHUB_ENV
+#         elif [ "${{ env.author }}" == "kanak_gupta" ]; then
+#           echo "USER_ID=${{ secrets.KHUSHI_USERNAME }}" >> $GITHUB_ENV
+#           echo "API_KEY=${{ secrets.DEEPAK_API_KEY }}" >> $GITHUB_ENV
+#         elif [ "${{ env.author }}" == "chenna_kesava" ]; then
+#           echo "USER_ID=${{ secrets.CHENNA_USERNAME }}" >> $GITHUB_ENV
+#           echo "API_KEY=${{ secrets.CHENNA_API_KEY }}" >> $GITHUB_ENV
+#         else
+#           echo "Unknown author. Exiting."
+#           exit 1
+#         fi
+
+#     - name: Delete resources
+#       id: delete-resources
+#       run: |
+#         echo "Deleting resources using file: ${{ env.file }}"
+#         docker run --rm -i \
+#           -v $GITHUB_WORKSPACE/.dataos:/dataos \
+#           -v $GITHUB_WORKSPACE:/jobsfolder \
+#           -e DATAOS_CONFIG_DIRECTORY=/dataos \
+#           -e USER_ID=${{ env.USER_ID }} \
+#           -e DATAOS_PRIME_APIKEY=${{ secrets.DATAOS_PRIME_APIKEY }} \
+#           -e LICENSE_KEY=${{ secrets.LICENSE_KEY }} \
+#           -e LICENSE_ORGANIZATION_ID=${{ secrets.LICENSE_ORGANIZATION_ID }} \
+#           -e DATAOS_FQDN=liberal-donkey.dataos.app \
+#           -e APIKEY=${{ env.API_KEY }} \
+#           rubiklabs/dataos-ctl:2.10.9-dev delete -f /jobsfolder/${{ env.file }}
+#       continue-on-error: true
+#       env:
+#         USER_ID: ${{ env.USER_ID }}
+#         API_KEY: ${{ env.API_KEY }}
+
+#     - name: Check delete result
+#       if: steps.delete-resources.outcome == 'failure'
+#       run: |
+#         echo "Initial delete failed. Waiting for 30 seconds and retrying..."
+#         sleep 30
+#         echo "Retrying delete..."
+#         docker run --rm -i \
+#           -v $GITHUB_WORKSPACE/.dataos:/dataos \
+#           -v $GITHUB_WORKSPACE:/jobsfolder \
+#           -e DATAOS_CONFIG_DIRECTORY=/dataos \
+#           -e USER_ID=${{ env.USER_ID }} \
+#           -e DATAOS_PRIME_APIKEY=${{ secrets.DATAOS_PRIME_APIKEY }} \
+#           -e LICENSE_KEY=${{ secrets.LICENSE_KEY }} \
+#           -e LICENSE_ORGANIZATION_ID=${{ secrets.LICENSE_ORGANIZATION_ID }} \
+#           -e DATAOS_FQDN=liberal-donkey.dataos.app \
+#           -e APIKEY=${{ env.API_KEY }} \
+#           rubiklabs/dataos-ctl:2.10.9-dev delete -f /jobsfolder/${{ env.file }}
+#       env:
+#         USER_ID: ${{ env.USER_ID }}
+#         API_KEY: ${{ env.API_KEY }}
+
+#     - name: Apply configuration
+#       run: |
+#         docker run --rm -i \
+#           -v $GITHUB_WORKSPACE/.dataos:/dataos \
+#           -v $GITHUB_WORKSPACE:/jobsfolder \
+#           -e DATAOS_CONFIG_DIRECTORY=/dataos \
+#           -e USER_ID=${{ env.USER_ID }} \
+#           -e DATAOS_PRIME_APIKEY=${{ secrets.DATAOS_PRIME_APIKEY }} \
+#           -e LICENSE_KEY=${{ secrets.LICENSE_KEY }} \
+#           -e LICENSE_ORGANIZATION_ID=${{ secrets.LICENSE_ORGANIZATION_ID }} \
+#           -e DATAOS_FQDN=liberal-donkey.dataos.app \
+#           -e APIKEY=${{ env.API_KEY }} \
+#           rubiklabs/dataos-ctl:2.10.9-dev apply -f /jobsfolder/${{ env.file }} -l
+
+#       env:
+#         USER_ID: ${{ env.USER_ID }}
+#         API_KEY: ${{ env.API_KEY }}
+
+#     - name: Apply configuration without linter
+#       run: |
+#         docker run --rm -i \
+#           -v $GITHUB_WORKSPACE/.dataos:/dataos \
+#           -v $GITHUB_WORKSPACE:/jobsfolder \
+#           -e DATAOS_CONFIG_DIRECTORY=/dataos \
+#           -e USER_ID=${{ env.USER_ID }} \
+#           -e DATAOS_PRIME_APIKEY=${{ secrets.DATAOS_PRIME_APIKEY }} \
+#           -e LICENSE_KEY=${{ secrets.LICENSE_KEY }} \
+#           -e LICENSE_ORGANIZATION_ID=${{ secrets.LICENSE_ORGANIZATION_ID }} \
+#           -e DATAOS_FQDN=liberal-donkey.dataos.app \
+#           -e APIKEY=${{ env.API_KEY }} \
+#           rubiklabs/dataos-ctl:2.10.9-dev apply -f /jobsfolder/${{ env.file }}
+#       env:
+#         USER_ID: ${{ env.USER_ID }}
+#         API_KEY: ${{ env.API_KEY }}
+      
+#     env:
+#       DATAOS_PRIME_APIKEY: ${{ secrets.DATAOS_PRIME_APIKEY }}
+#       LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
+#       LICENSE_ORGANIZATION_ID: ${{ secrets.LICENSE_ORGANIZATION_ID }}
+#       DOCKER_USERNAME_DATAOS: ${{ secrets.DOCKER_USERNAME_DATAOS }}
+#       DOCKER_PASSWORD_DATAOS: ${{ secrets.DOCKER_PASSWORD_DATAOS }}
+
+
+
+
 name: Deploy Streamlit App
 
 on:
@@ -8,30 +154,49 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
 
+    - name: Check for changes
+      id: check_changes
+      run: |
+        # Get the list of modified or added files
+        files=$(git diff --name-only HEAD~1 HEAD)
+        if [ -z "$files" ]; then
+          echo "No changes detected."
+          echo "RUN_DEPLOY=false" >> $GITHUB_ENV
+        else
+          echo "Changes detected: $files"
+          echo "RUN_DEPLOY=true" >> $GITHUB_ENV
+        fi
+
     - name: Set up Docker Buildx
+      if: env.RUN_DEPLOY == 'true'
       uses: docker/setup-buildx-action@v1
 
     - name: Login to Docker Hub
+      if: env.RUN_DEPLOY == 'true'
       run: docker login -u ${{ secrets.DOCKER_USERNAME_DATAOS }} -p ${{ secrets.DOCKER_PASSWORD_DATAOS }}
 
     - name: Pull Docker image
+      if: env.RUN_DEPLOY == 'true'
       run: docker pull rubiklabs/dataos-ctl:2.10.9-dev
 
     - name: Run Docker container
+      if: env.RUN_DEPLOY == 'true'
       run: docker run rubiklabs/dataos-ctl:2.10.9-dev
 
     - name: Find YAML file
+      if: env.RUN_DEPLOY == 'true'
       run: |
         file=$(find . -name "cluster.yaml" -printf "%P\n" -quit)
         echo "Found file: $file"
         echo "file=$file" >> $GITHUB_ENV
 
     - name: Get commit author
+      if: env.RUN_DEPLOY == 'true'
       id: get_author
       run: |
         commit_author=$(git log -1 --format='%an')
@@ -39,6 +204,7 @@ jobs:
         echo "author=$commit_author" >> $GITHUB_ENV
 
     - name: Set API Key and User ID
+      if: env.RUN_DEPLOY == 'true'
       id: set_env
       run: |
         if [ "${{ env.author }}" == "shreya negi" ]; then
@@ -59,6 +225,7 @@ jobs:
         fi
 
     - name: Delete resources
+      if: env.RUN_DEPLOY == 'true'
       id: delete-resources
       run: |
         echo "Deleting resources using file: ${{ env.file }}"
@@ -79,7 +246,7 @@ jobs:
         API_KEY: ${{ env.API_KEY }}
 
     - name: Check delete result
-      if: steps.delete-resources.outcome == 'failure'
+      if: env.RUN_DEPLOY == 'true' && steps.delete-resources.outcome == 'failure'
       run: |
         echo "Initial delete failed. Waiting for 30 seconds and retrying..."
         sleep 30
@@ -100,6 +267,7 @@ jobs:
         API_KEY: ${{ env.API_KEY }}
 
     - name: Apply configuration
+      if: env.RUN_DEPLOY == 'true'
       run: |
         docker run --rm -i \
           -v $GITHUB_WORKSPACE/.dataos:/dataos \
@@ -112,12 +280,12 @@ jobs:
           -e DATAOS_FQDN=liberal-donkey.dataos.app \
           -e APIKEY=${{ env.API_KEY }} \
           rubiklabs/dataos-ctl:2.10.9-dev apply -f /jobsfolder/${{ env.file }} -l
-
       env:
         USER_ID: ${{ env.USER_ID }}
         API_KEY: ${{ env.API_KEY }}
 
     - name: Apply configuration without linter
+      if: env.RUN_DEPLOY == 'true'
       run: |
         docker run --rm -i \
           -v $GITHUB_WORKSPACE/.dataos:/dataos \
@@ -133,10 +301,11 @@ jobs:
       env:
         USER_ID: ${{ env.USER_ID }}
         API_KEY: ${{ env.API_KEY }}
-      
+
     env:
       DATAOS_PRIME_APIKEY: ${{ secrets.DATAOS_PRIME_APIKEY }}
       LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
       LICENSE_ORGANIZATION_ID: ${{ secrets.LICENSE_ORGANIZATION_ID }}
       DOCKER_USERNAME_DATAOS: ${{ secrets.DOCKER_USERNAME_DATAOS }}
       DOCKER_PASSWORD_DATAOS: ${{ secrets.DOCKER_PASSWORD_DATAOS }}
+ 
